#!/bin/bash
if [ -f /sys/class/power_supply/BAT0/energy_now ]; then
	num1="$(cat /sys/class/power_supply/BAT0/energy_now)"
	num2="$(cat /sys/class/power_supply/BAT0/energy_full)"
else
	num1="$(cat /sys/class/power_supply/BAT0/charge_now)"
	num2="$(cat /sys/class/power_supply/BAT0/charge_full)"
fi

batAtual="$(echo "scale=2; 100 * $num1/$num2" | bc -l )"

status="$(cat /sys/class/power_supply/BAT0/status)"

echo "$batAtual%"

case $BUTTON in
    2) notify-send "Bateria atual:" "$batAtual% \n<b>Status:</b> \n$status" ;;
esac
