#!/bin/bash

atual=$(dunstctl is-paused)

if [[ $atual == "false" ]]; then
    notify-send "Desativando notificações." -t 1000
    sleep 1
    dunstctl set-paused true
else
    notify-send "Ativando notificações." -t 1000
    dunstctl set-paused false
fi


